UPDATE `spt`.`permissions` SET `permissions` = 'показ в меню,отчет по количеству преподаваемых часов,общий отчет по кадрам' WHERE (`java_class_name` = 'HRReportsView');

UPDATE `spt`.`user_permission` SET `permissions` = 'HRReportsView:показ в меню,отчет по количеству преподаваемых часов,общий отчет по кадрам' WHERE (`role_name` = 'hr') and (`permissions` = 'HRReportsView:показ в меню,отчет по количеству преподаваемых часов');
UPDATE `spt`.`user_permission` SET `permissions` = 'HRReportsView:показ в меню,отчет по количеству преподаваемых часов,общий отчет по кадрам' WHERE (`role_name` = 'admin') and (`permissions` = 'HRReportsView:показ в меню,отчет по количеству преподаваемых часов');

UPDATE `spt`.`gender` SET `name` = 'Мужской' WHERE (`id` = '1');
UPDATE `spt`.`gender` SET `name` = 'Женский' WHERE (`id` = '2');
delete ignore from nationality;
update employee set nationality_id = 127 where nationality_id = 128;
update employee set nationality_id = 93 where nationality_id = 187;
UPDATE `spt`.`nationality` SET `name` = 'Афганец' WHERE (`id` = '1');
UPDATE `spt`.`nationality` SET `name` = 'Австралиец' WHERE (`id` = '9');
UPDATE `spt`.`nationality` SET `name` = 'Азербайжанец' WHERE (`id` = '11');
UPDATE `spt`.`nationality` SET `name` = 'Канадец' WHERE (`id` = '31');
UPDATE `spt`.`nationality` SET `name` = 'Эфиоп' WHERE (`id` = '58');
UPDATE `spt`.`nationality` SET `name` = 'Немец' WHERE (`id` = '65');
UPDATE `spt`.`nationality` SET `name` = 'Индус' WHERE (`id` = '77');
UPDATE `spt`.`nationality` SET `name` = 'Индонезиец' WHERE (`id` = '78');
UPDATE `spt`.`nationality` SET `name` = 'Японец' WHERE (`id` = '85');
UPDATE `spt`.`nationality` SET `name` = 'Казах' WHERE (`id` = '87');
UPDATE `spt`.`nationality` SET `name` = 'Кениец' WHERE (`id` = '88');
UPDATE `spt`.`nationality` SET `name` = 'Кыргыз' WHERE (`id` = '93');
UPDATE `spt`.`nationality` SET `name` = 'Литовец' WHERE (`id` = '101');
UPDATE `spt`.`nationality` SET `name` = 'Монгол' WHERE (`id` = '117');
UPDATE `spt`.`nationality` SET `name` = 'Нигериец' WHERE (`id` = '127');
DELETE FROM `spt`.`nationality` WHERE (`id` = '128');
UPDATE `spt`.`nationality` SET `name` = 'Пакистанец' WHERE (`id` = '131');
UPDATE `spt`.`nationality` SET `name` = 'Филипинец' WHERE (`id` = '137');
UPDATE `spt`.`nationality` SET `name` = 'Португалец' WHERE (`id` = '139');
UPDATE `spt`.`nationality` SET `name` = 'Русский' WHERE (`id` = '142');
UPDATE `spt`.`nationality` SET `name` = 'Серб' WHERE (`id` = '151');
UPDATE `spt`.`nationality` SET `name` = 'Южноафриканец' WHERE (`id` = '159');
UPDATE `spt`.`nationality` SET `name` = 'Таджик' WHERE (`id` = '169');
UPDATE `spt`.`nationality` SET `name` = 'Таец' WHERE (`id` = '171');
UPDATE `spt`.`nationality` SET `name` = 'Турок' WHERE (`id` = '176');
UPDATE `spt`.`nationality` SET `name` = 'Туркмен' WHERE (`id` = '177');
UPDATE `spt`.`nationality` SET `name` = 'Украинец' WHERE (`id` = '180');
UPDATE `spt`.`nationality` SET `name` = 'Британец' WHERE (`id` = '182');
UPDATE `spt`.`nationality` SET `name` = 'Американец' WHERE (`id` = '183');
UPDATE `spt`.`nationality` SET `name` = 'Узбек' WHERE (`id` = '185');
UPDATE `spt`.`nationality` SET `name` = 'Замбиец' WHERE (`id` = '191');
DELETE FROM `spt`.`nationality` WHERE (`id` = '187');
UPDATE `spt`.`nationality` SET `name` = 'Калмык' WHERE (`id` = '193');
UPDATE `spt`.`nationality` SET `name` = 'Уйгур' WHERE (`id` = '194');
UPDATE `spt`.`nationality` SET `name` = 'Дунганин' WHERE (`id` = '195');
UPDATE `spt`.`nationality` SET `name` = 'Татарин' WHERE (`id` = '196');
UPDATE `spt`.`nationality` SET `name` = 'Чеченец' WHERE (`id` = '197');
UPDATE `spt`.`nationality` SET `name` = 'Карачаец' WHERE (`id` = '198');
UPDATE `spt`.`nationality` SET `name` = 'Лезгин' WHERE (`id` = '199');
UPDATE `spt`.`nationality` SET `name` = 'Курд' WHERE (`id` = '200');
UPDATE `spt`.`nationality` SET `name` = 'Багамец' WHERE (`id` = '12');
UPDATE `spt`.`nationality` SET `name` = 'Ганец' WHERE (`id` = '66');
UPDATE `spt`.`nationality` SET `name` = 'Иракиец' WHERE (`id` = '80');
UPDATE `spt`.`nationality` SET `name` = 'Араб' WHERE (`id` = '149');
UPDATE `spt`.`nationality` SET `name` = 'Зимбабвец' WHERE (`id` = '192');
INSERT INTO `spt`.`acc_category` (`name`, `parent_code`, `code`, `parent_id`, `acc_type_id`, `activity_status_id`, `school_id`, `employee_id`) VALUES ('SADIRBAYEV URMAT', '791.02.14', '104122', '3229', '2', '2', '5', '4012');

delete ignore FROM spt.hr_country;

UPDATE `spt`.`hr_country` SET `name` = 'Афганистан' WHERE (`id` = '397');
UPDATE `spt`.`hr_country` SET `name` = 'Босния и Герцеговина' WHERE (`id` = '423');
UPDATE `spt`.`hr_country` SET `name` = 'Канада' WHERE (`id` = '434');
UPDATE `spt`.`hr_country` SET `name` = 'Китай' WHERE (`id` = '440');
UPDATE `spt`.`hr_country` SET `name` = 'Финляндия' WHERE (`id` = '468');
UPDATE `spt`.`hr_country` SET `name` = 'Германия' WHERE (`id` = '476');
UPDATE `spt`.`hr_country` SET `name` = 'Гана' WHERE (`id` = '477');
UPDATE `spt`.`hr_country` SET `name` = 'Индонезия' WHERE (`id` = '496');
UPDATE `spt`.`hr_country` SET `name` = 'Ирак' WHERE (`id` = '498');
UPDATE `spt`.`hr_country` SET `name` = 'Казакстан' WHERE (`id` = '505');
UPDATE `spt`.`hr_country` SET `name` = 'Кыргызстан' WHERE (`id` = '510');
UPDATE `spt`.`hr_country` SET `name` = 'Монголия' WHERE (`id` = '537');
UPDATE `spt`.`hr_country` SET `name` = 'Нигерия' WHERE (`id` = '551');
UPDATE `spt`.`hr_country` SET `name` = 'Филиппины' WHERE (`id` = '563');
UPDATE `spt`.`hr_country` SET `name` = 'Португалия' WHERE (`id` = '566');
UPDATE `spt`.`hr_country` SET `name` = 'Россия' WHERE (`id` = '571');
UPDATE `spt`.`hr_country` SET `name` = 'Южная Африка' WHERE (`id` = '591');
UPDATE `spt`.`hr_country` SET `name` = 'Таджикистан' WHERE (`id` = '602');
UPDATE `spt`.`hr_country` SET `name` = 'Турция' WHERE (`id` = '611');
UPDATE `spt`.`hr_country` SET `name` = 'Туркменистан' WHERE (`id` = '612');
UPDATE `spt`.`hr_country` SET `name` = 'Великобритания' WHERE (`id` = '617');
UPDATE `spt`.`hr_country` SET `name` = 'США' WHERE (`id` = '618');
UPDATE `spt`.`hr_country` SET `name` = 'Узбекистан' WHERE (`id` = '621');
UPDATE `spt`.`hr_country` SET `name` = 'Венесуэлла' WHERE (`id` = '623');
UPDATE `spt`.`hr_country` SET `name` = 'Замбия' WHERE (`id` = '630');
